[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lsy_drone_racing"
version = "0.0.1"
description = "LSY Autonomous Drone Racing Project Course"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
]

dependencies = [
  "fire>=0.6.0",
  "numpy>=2.0.0",
  "toml>=0.10.2",
  "gymnasium[array-api]>=1.2.0",
  "ml-collections>=1.0",
  "packaging>=24.0",
  "drone-models",
  "drone-controllers",
  "crazyflow@git+https://github.com/utiasDSL/crazyflow.git@0.1.0b0",
  "jax>=0.7",
  "warp-lang",
  "jax[cuda12]",
  "torch==2.8.0"
]

[tool.setuptools.packages]
find = {}

