[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lsy_drone_racing"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "array-api-compat>=1.14.0",
    "crazyflow",
    "fire >= 0.6.0",
    "gymnasium>=1.2.3",
    "jax[cuda12]>=0.8.1",
    "numpy",
    "opencv-python>=4.13.0.92",
    "toml >= 0.10.2",
    "torch>=2.10.0",
    "warp-lang>=1.12.0",
    "orbslam3",
]

[project.optional-dependencies]
# This allows 'uv sync --extra sim' to work
sim = [
    "gymnasium[array-api] >= 1.2.0",
    "ml-collections >= 1.0",
    "packaging >= 24.0",
    "drone-models", 
    "drone-controllers",
    "warp-lang",
]

[dependency-groups]
dev = [
    "pytest >= 8.0.0",
    "ruff",
]
submission = [
    "pandas",
    "kaggle",
]

[tool.setuptools]
packages = ["lsy_drone_racing"]


[tool.uv.sources]
crazyflow = { git = "https://github.com/utiasDSL/crazyflow.git", rev = "0.1.0b0" }
orbslam3 = { git = "https://github.com/Robaire/orbslam3-python.git" }
